window.PROJECTS = [
  {
    id: 1,
    title: "E-Commerce Platform",
    category: "Web App",
    emoji: "🛒",
    image: "images/business.jpg",
    desc: "Full-stack shop with React & Node.js, Stripe payments, real-time inventory.",
    fullDesc:
      "A full-featured e-commerce platform built with React on the frontend and Node.js + Express on the backend. Features include product management, shopping cart, Stripe payment integration, order tracking, and an admin dashboard. Deployed on Google Cloud Platform with MongoDB Atlas.",
    tags: "React,Node.js,MongoDB,Stripe,Tailwind CSS",
    featured: true,
    liveUrl: "https://example.com",
    githubUrl: "https://github.com/mehedihasan",
  },
  {
    id: 2,
    title: "AI Chat Interface",
    category: "AI",
    emoji: "🤖",
    image: "",
    desc: "GPT-powered chat application with conversation history and custom personas.",
    fullDesc:
      "A sleek AI-powered chat interface built on top of OpenAI's GPT API. Users can create custom AI personas, save conversation history, and export chats as PDF. Built with React, Python FastAPI backend, and PostgreSQL for persistence.",
    tags: "React,Python,OpenAI,FastAPI,PostgreSQL",
    featured: true,
    liveUrl: "",
    githubUrl: "https://github.com/mehedihasan",
  },
  {
    id: 3,
    title: "Analytics Dashboard",
    category: "Dashboard",
    emoji: "📊",
    image: "",
    desc: "Real-time KPI dashboard with beautiful charts and live data streaming.",
    fullDesc:
      "A real-time analytics dashboard that visualises business KPIs using D3.js charts. Data streams via WebSocket from a Node.js server. Features include date-range filters, export to CSV/PDF, dark/light mode, and role-based access control.",
    tags: "Vue.js,D3.js,Node.js,WebSocket,Firebase",
    featured: false,
    liveUrl: "",
    githubUrl: "https://github.com/mehedihasan",
  },
  {
    id: 4,
    title: "Portfolio CMS",
    category: "Web App",
    emoji: "💼",
    image: "",
    desc: "Google Sheets-powered portfolio CMS built with Google Apps Script.",
    fullDesc:
      "A portfolio website where all project content is managed from a Google Sheets spreadsheet. Built with Google Apps Script (HTML service), the site dynamically renders project cards pulled from the sheet, supports category filtering, and includes a contact form that sends emails via MailApp.",
    tags: "Apps Script,HTML,CSS,JavaScript,Google Sheets",
    featured: false,
    liveUrl: "",
    githubUrl: "https://github.com/mehedihasan",
  },
  {
    id: 5,
    title: "Mobile Fitness App",
    category: "Mobile",
    emoji: "🏋️",
    image: "",
    desc: "Cross-platform workout tracker built in Flutter with Firebase backend.",
    fullDesc:
      "A Flutter-based fitness tracking app supporting iOS and Android. Users can log workouts, set goals, track progress with charts, and follow guided exercise routines. Firebase Firestore stores user data in real time, and Firebase Auth handles authentication.",
    tags: "Flutter,Dart,Firebase,Firestore",
    featured: false,
    liveUrl: "",
    githubUrl: "https://github.com/mehedihasan",
  },
  {
    id: 6,
    title: "DevOps Pipeline Tool",
    category: "DevOps",
    emoji: "⚙️",
    image: "",
    desc: "CI/CD automation with Docker, GitHub Actions, and AWS ECS deployment.",
    fullDesc:
      "An internal DevOps tooling project that standardises CI/CD pipelines across multiple services. Uses GitHub Actions for build/test/deploy, Docker containers for consistent environments, and deploys to AWS ECS via ECR. Includes Slack notifications and rollback automation.",
    tags: "Docker,GitHub Actions,AWS,Bash,Terraform",
    featured: false,
    liveUrl: "",
    githubUrl: "https://github.com/mehedihasan",
  },
];
